[package]
name = "joker"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
num_cpus = "1.16"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
